sudo: false
env:
  - NPM_SCRIPT=lint
  - NPM_SCRIPT=benchmark
  - NPM_SCRIPT=coverage
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 'stable'
before_install:
  - npm i -g typings
  - typings install
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
  - npm run $NPM_SCRIPT
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
